[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer-runs = 10_000
verbosity = 3

ignored_warnings_from = ["lib", "test", "script"]

no_match_coverage = "script|test"

[fmt]
bracket_spacing = true
line_length = 140
single_line_statement_block = "single"
multiline_func_header = "params_first_multi"
